### ISSUE TITLE
模型输出图片在白色区域会有彩色斑块

### ISSUE THREAD

**Issue by meton-robean** [jackiesdd/raindropAttention#1]
你好，请问你们在测试Qian的模型时，他的输出图片结果在图片的白色区域（例如天空，白墙区域）会有彩色板块吗？ 我遇到这样的问题。
![image](https://user-images.githubusercontent.com/17881739/68729583-580be880-0605-11ea-8b59-c5f318a9081f.png)

**Comment by jackiesdd** [comment]
你好！
我们在使用Qian的代码也出现过类似的问题





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"meton-robean"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月13日(星期三) 中午11:04
收件人:&nbsp;"jackiesdd/raindropAttention"<raindropAttention@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[jackiesdd/raindropAttention] 模型输出图片在白色区域会有彩色斑块 (#1)




你好，请问你们在测试Qian的模型时，他的输出图片结果在图片的白色区域（例如天空，白墙区域）会有彩色板块吗？ 我遇到这样的问题。

**Comment by meton-robean** [comment]
那最后怎么解决的呢？

**Comment by jackiesdd** [comment]
你好！
我做实验时发现Qian的模型会有这样的一小块雨滴变成彩色块的现象，和您遇到的问题可能不完全一样。这个问题个人建议咨询代码原作者会更好。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"meton-robean"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月14日(星期四) 凌晨0:01
收件人:&nbsp;"jackiesdd/raindropAttention"<raindropAttention@noreply.github.com&gt;;
抄送:&nbsp;"bgzc"<594503295@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [jackiesdd/raindropAttention] 模型输出图片在白色区域会有彩色斑块 (#1)




那最后怎么解决的呢？
